'use strict';
const key='qd-lab-progress-v1';let completed=[];let available=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))completed=saved.filter(id=>MODULES.some(m=>m.id===id));}catch{available=false;}
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
document.getElementById('nav').innerHTML=MODULES.map((m,i)=>`<a href="#${m.id}"><span>${String(i+1).padStart(2,'0')}</span>${e(m.zh)}</a>`).join('');
document.getElementById('modules').innerHTML=MODULES.map((m,i)=>`<details class="module ${completed.includes(m.id)?'done':''}" id="${m.id}" ${i===0?'open':''}><summary><span class="num">${String(i+1).padStart(2,'0')}</span><span class="titles"><b>${e(m.title)}</b><small>${e(m.zh)} · ${e(m.phase)}</small></span><span class="meta">${e(m.time)}</span><span class="chevron" aria-hidden="true">+</span></summary><div class="body"><span class="label">LEARNING OBJECTIVE / 学习目标</span><p class="goal">${e(m.goal)}</p><span class="label">SEQUENCE / 建议学习顺序</span><div class="sequence">${e(m.order)}</div><span class="label">READ & STUDY / 推荐资料 · 按阅读顺序</span>${m.resources.map(r=>`<article class="resource"><div class="resource-head"><a href="${e(r.url)}" target="_blank" rel="noopener noreferrer">${e(r.name)}</a><span class="tag ${r.kind==='仅配套代码开放'?'amber':''}">${e(r.kind)}</span></div><p>${e(r.why)}</p><div class="reading">重点阅读：${e(r.read)}</div></article>`).join('')}<div class="practice"><div><span class="label">BUILD / 项目练习</span><p>${e(m.project)}</p></div><div><span class="label">VERIFY / 验收标准</span><p>${e(m.accept)}</p></div></div><label class="check"><input type="checkbox" data-id="${m.id}" ${completed.includes(m.id)?'checked':''}>我已完成学习与项目验收</label></div></details>`).join('');
function update(){document.getElementById('count').textContent=String(completed.length).padStart(2,'0');document.getElementById('progress').value=completed.length;if(!available)document.getElementById('storage').textContent='浏览器存储不可用，进度仅保留至本次关闭';}
document.querySelectorAll('input[data-id]').forEach(input=>input.addEventListener('change',()=>{completed=completed.filter(id=>id!==input.dataset.id);if(input.checked)completed.push(input.dataset.id);input.closest('details').classList.toggle('done',input.checked);try{localStorage.setItem(key,JSON.stringify(completed));}catch{available=false;}update();}));
function syncButton(){const all=[...document.querySelectorAll('.module')].every(d=>d.open);document.getElementById('expand').textContent=all?'折叠全部':'展开全部';}
document.getElementById('expand').addEventListener('click',()=>{const all=[...document.querySelectorAll('.module')].every(d=>d.open);document.querySelectorAll('.module').forEach(d=>d.open=!all);syncButton();});document.querySelectorAll('.module').forEach(d=>d.addEventListener('toggle',syncButton));
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector(a.getAttribute('href')).open=true;}));
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+entry.target.id));}},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('.module').forEach(d=>observer.observe(d));update();
