'use strict';
const lcHost = document.querySelector('#m12 .body');
const lcSection = document.createElement('section');lcSection.className='leetcode';
const sources=[
['E1','Citadel NXT · SWE · 首轮（页面未提供明确面试日期）','候选人明确描述 insert / findMedian，对应 LC 295；这是单篇自述，不代表 NXT 所有岗位。','https://leetcode.com/discuss/post/6972253/citadel-nxt-first-interview-experience-b-6w1v/'],
['E2','Citadel · NYC SWE · 2020-02','报告包含链表环、带容量/时间限制的消息 producer、跨调用分片解析。LC 141 是同类题；其余需要独立实现练习。旧样本保留用于题型，不当作当前流程。','https://leetcode.com/discuss/post/619324/citadel-software-engineer-nyc-feb-2020/'],
['E3','Optiver · London SWE Intern · 2022 OA / Summer 2023','报告为可更新分红事件与未来价格查询。LC 2034 仅练在线修正的相邻能力，不是同一道题；真正追问见下方分红练习。','https://leetcode.com/discuss/post/2730450/'],
['E4','IMC · New Delhi SWE · 2026-08（发布 2026-09-02）','匿名报告提到实现 pro-rata order book。LC 1801 是双堆积压模拟，不能替代按比例分配、撤单或真实订单簿。','https://www.glassdoor.com/Interview/IMC-Trading-Software-Engineer-Interview-Questions-EI_IE278100.0,11_KO12,29.htm'],
['E5','HRT · SWE New Grad · 2019 OA','报告涉及负二进制，并直接给出 LC 1017 的相关链接。属于历史单样本，相近题而非已验证当前原题。','https://leetcode.com/discuss/post/394944/Hudson-River-Trading-or-OA-2019-or-SWE-New-Grad/'],
['E6','HRT · OA Two rooks · 历史帖子（页面未提供明确日期）','报告为矩阵上两个不同行、不同列位置的最大和。没有硬映射成 LeetCode 三车题；保留成优化练习。','https://leetcode.com/discuss/post/889638/hudson-river-trading-oa-two-rooks/'],
['E7','DRW · Amsterdam Quant dev/SWE Intern · 2023-10','候选人称 OA 有两题；随后讨论流式算法与系统知识。它支持准备流式数据结构的方向，无法证明某个 LC 题号出现过。','https://www.wallstreetoasis.com/company/drw/interview/quant-devswe'],
['E8','Optiver · Chicago New Grad SWE · 2024 招聘季','匿名报告描述 OOP 代码补全、C++ 实现与系统设计，支持增加实现类练习。','https://leetcode.com/discuss/post/4126574/Optiver-New-Grad-SWE-2024-%28Chicago%29-Interview-Process-Rejection/'],
['O1','Optiver 官方 · 2025-03-21','强调容器内部实现、复杂度、内存表示及设计解释；技术面试不依赖标准 LeetCode 谜题。说明适用范围不必与每个 OA 完全相同。','https://prod-www.optiver.com/join-us/stories/optiver-interview-tips-for-software-engineers/'],
['O2','Jane Street 官方 · SWE 准备说明','强调协作编程、熟悉语言和开放式追问；不应将 Trader 的心算、概率题直接混入 SWE 主线。','https://www.janestreet.com/preparing-for-a-software-engineering-interview/']
];
const link=(url,name)=>`<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(name)}</a>`;
lcSection.innerHTML=`<span class="label">QD CODING / RESEARCHED ROADMAP</span><h3>63 道算法题 + 6 个实现练习</h3><p>针对交易公司 SWE / Quant Developer 的 coding 部分：36 题通用核心（P0）、12 题数据结构与模拟（P1）、15 题进阶 OA（P2）。P0/P1 是学习优先级，不是面试出现频率。核对日期：2026-10-06。</p><p>这次从候选人原帖与公司官方说明出发，再用成熟题单补齐算法覆盖。样本横跨办公室、级别与年份；没有可靠分母可算“QD 高频率”。明确题目、相近题与编辑补充分开列。Trader / QR / ML 的题型不纳入通用 QD 主线。</p><details class="lc-group" open><summary>研究依据：哪些题型有证据？</summary><div class="lc-evidence">${sources.map(s=>`<article id="qd-${s[0]}"><b>${s[0]} · ${escapeHtml(s[1])}</b><p>${escapeHtml(s[2])}</p>${link(s[3],'查看原始来源')}</article>`).join('')}</div><p>O：公司官方说明，支持面试能力与形式；E：候选人自述，未经公司独立验证。单条 LC 映射只在题型足够明确时给出。无法核对原帖的付费公司标签、聚合站“最近六个月常考”、求助帖不作直接题目证据。</p></details>
<details class="lc-group" open><summary>如何结合 Blind 75 / Grind 75 / NeetCode 150 / Top 150</summary><div class="lc-evidence"><article><b>Blind 75：模式复习</b><p>以经典题型作基础；本页标出 NeetCode 作者公开数据中的 Blind75 归属，避免把“官方 LeetCode 75”混为 Blind75。</p>${link('https://www.techinterviewhandbook.org/best-practice-questions/','Blind75 作者说明')}</article><article><b>Grind 75：有优先级的练习计划</b><p>本页按作者当前公开数据的前 75 题标记 Grind75，后续题标记“Grind 扩展池”。你改变时间/主题设置后，生成的题单会变化。它的通用频率评分不是 QD 公司统计。</p>${link('https://www.techinterviewhandbook.org/grind75','Grind75')} · ${link('https://www.techinterviewhandbook.org/grind75/about','作者方法')}</article><article><b>NeetCode 150：补齐模式与讲解</b><p>逐题标签来自作者仓库的 blind75 / neetcode150 字段。优先做本页 P0，再用 NC150 复习薄弱主题；订单簿、分片解析不应被刷完 150 题替代。</p>${link('https://neetcode.io/practice/practice/neetcode150','NC150')} · ${link('https://github.com/neetcode-gh/leetcode/blob/main/.problemSiteData.json','题单归属数据')}</article><article><b>Top 150：扩大通用覆盖</b><p>这里把 Top150 明确理解为 LeetCode Top Interview 150。用于更广的数组、字符串、树图与 DP 复习；不作为 QD 高频题证据。该站动态题单未完整提取，因此本页不猜测逐题 Top150 标签。</p>${link('https://leetcode.com/studyplan/top-interview-150/','Top Interview 150')}</article></div><p>题单交集表示通用准备共识，不表示交易公司会问。没有归属标签的题是本路线补充，或归属未核实；它不表示所有其他题单都排除了该题。</p></details>
<div class="practice"><div><span class="label">ORDER / 推荐顺序</span><p>第 1–4 周：P0 按主题顺序，基础熟练可跳 Easy。第 5–6 周：P1 + 下方实现练习；先 LRU、环形队列、时间索引，再订单状态。第 7–8 周：按目标岗位选 P2，与 45 分钟模拟交替。每周 8–10 小时仅是规划参考。</p></div><div><span class="label">ROLE / 按岗位调整</span><p>低延迟 C++ / Core Dev：加重 P1、解析、生命周期与性能解释；Algo Dev / OA 较强岗位：加强 P2 图与 DP；Jane Street SWE：开放式模拟与逐步扩展优先。具体语言和面试形式以邀请与 recruiter 信息为准。</p></div></div>
<p>下面每题提供官方题面、难度、题单交集与复习追问。题面可公开阅读，提交通常需登录；题解与公司标签可能收费。刷题进度仅保存在当前浏览器，与模块进度分开。</p><div class="lc-progress" id="lc-progress" aria-live="polite"></div>`+
QD_INTERVIEW.map((g,i)=>`<details class="lc-group" ${i===0?'open':''}><summary>${g.tier} / ${escapeHtml(g.title)} <small> · ${g.questions.length} 题</small></summary><p>${escapeHtml(g.why)}</p>${g.questions.map(q=>`<article class="lc-question"><div class="lc-row"><label><input type="checkbox" data-lc="${q.id}" aria-label="完成 ${q.id} ${escapeHtml(q.name)}"> <span class="lc-id">#${q.id}</span></label>${link('https://leetcode.com/problems/'+q.slug+'/',q.name)}<span class="lc-difficulty ${q.difficulty.toLowerCase()}">${q.difficulty}</span></div><div class="lc-badges">${q.lists.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}${q.evidence?`<a href="#qd-${q.evidence}">${q.evidence} · ${[141,295].includes(q.id)?'自述同类题':'相近练习'}</a>`:'<small>编辑选题 · 未找到题号级直接面经依据</small>'}</div><p>${escapeHtml(q.note)}</p></article>`).join('')}</details>`).join('')+
`<details class="lc-group" open><summary>6 个实现型面试练习 · 不靠 LeetCode AC 代替</summary><div class="lc-evidence"><article><b>01 / 增量消息 decoder · E2</b><p>自己设计长度前缀协议和 feed(bytes) API。长度字段/消息体可能分片，也可能粘连；明确最大长度与非法数据策略。验收：逐字节喂入与一次喂入结果一致，半个消息不输出。</p></article><article><b>02 / 有界批量 producer · E2</b><p>支持条数上限、最长等待、flush 和 shutdown。先单线程 fake clock 验证状态，再讨论并发、背压与发送失败；不要把实际跨进程内存同步当普通 mutex 即可解决。验收：容量和 deadline 不变量、关闭残留与失败重试明确。</p></article><article><b>03 / 可修改分红事件查询 · E3</b><p>由你明确定义 update(id,date,amount) 和 price(day)，保留朴素扫描 oracle，再用坐标压缩 + Fenwick tree 优化前缀查询；日期不预知时讨论有序结构。验收：同 ID 修正/日期变更不重复计扣，查询端点一致。</p></article><article><b>04 / 撮合与订单簿 · E4</b><p>分两个独立契约练：price-time FIFO，以及单价格档 pro-rata。用价格索引、订单 ID 索引和队列；明确整数份额取整、余量分配、amend 与 cancel。面经未披露完整规则，这些是自定练习规格。验收：数量守恒、索引一致、全量/部分成交、未知 ID、同价顺序。</p></article><article><b>05 / Two rooks 优化 · E6</b><p>自定矩阵允许值和尺寸，找两个不同行不同列的元素最大和。先暴力 oracle，再保留每行候选/全局候选减少组合；证明候选保留数量足够。验收：随机小矩阵与 oracle 比对，并覆盖不足两行/列、并列最大值。</p></article><article><b>06 / 开放式 Memo / 状态追问 · O2</b><p>阅读 Jane Street 已退役示例，练逐阶段扩展与解释，而非背当前真题。模拟时每次增加一个约束并修改数据结构，保持 API 和测试可运行。</p>${link('https://blog.janestreet.com/what-a-jane-street-dev-interview-is-like/','Jane Street 官方退役示例')}</article></div></details><div class="practice"><div><span class="label">VERIFY / 做完的标准</span><p>能不看答案重写，并讲不变量、平均/最坏复杂度、STL 所有权与分配成本。做题后 1 天和 7 天重做；模拟先澄清契约，再逐步优化，最后手动跑边界例子。</p></div><div><span class="label">LIMIT / 为什么不叫高频榜</span><p>这是一套有来源的准备路线。历史面经只能说明题型曾被报告；公司、岗位和地区不同，不据此推算概率。P2 不是低价值废题，而是在当前目标下可以后做。</p></div></div>`;
lcHost.insertBefore(lcSection,lcHost.querySelector('.check'));
const lcKey='path2qd-algorithm-progress-v1';let solved=[];let lcStorage=true;
try{const v=JSON.parse(localStorage.getItem(lcKey)||'[]');if(Array.isArray(v))solved=v.filter(n=>QD_INTERVIEW.some(g=>g.questions.some(q=>q.id===n)));}catch{lcStorage=false;}
function updateLc(){document.getElementById('lc-progress').textContent=`算法进度 ${solved.length} / 63 · ${lcStorage?'保存在当前浏览器':'存储不可用，仅本次会话'}`;}
lcSection.querySelectorAll('[data-lc]').forEach(c=>{c.checked=solved.includes(Number(c.dataset.lc));c.addEventListener('change',()=>{const n=Number(c.dataset.lc);solved=solved.filter(x=>x!==n);if(c.checked)solved.push(n);try{localStorage.setItem(lcKey,JSON.stringify(solved));}catch{lcStorage=false;}updateLc();});});
lcSection.querySelectorAll('a[href^="#qd-"]').forEach(a=>a.addEventListener('click',()=>{document.getElementById(a.hash.slice(1)).closest('details').open=true;}));updateLc();
